insert into food
  (name,
  author,
  reference,
  description,
  "prepTime",
  "cookTime",
  keywords,
  servings,
  category,
  cuisine,
  calories,
  ingredients,
  instructions,
  "additionalNotes")
values
  ('Example Dish',
  'Test User',
  'https://google.com',
  'example description',
  5,
  10,
  '{"one","two"}',
  5,
  'yummy food',
  'cuisine mmm',
  500,
  '{"stick of butter","love"}',
  '{"preheat oven to 375","grease 9x13 pan"}',
  '{"note", "note2"}')