create table
  public.food (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    author text null,
    reference text null,
    description text null,
    "prepTime" smallint null default '0'::smallint,
    "cookTime" smallint null default '0'::smallint,
    keywords text[] null,
    servings smallint null default '0'::smallint,
    category text null,
    cuisine text null,
    calories smallint null default '0'::smallint,
    ingredients text[] null,
    instructions text[] null,
    "additionalNotes" text[] null,
    constraint food_pkey primary key (id)
  ) tablespace pg_default;